# Generated by Django 5.2.6 on 2025-09-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=70)),
                ('color', models.CharField(blank=True, max_length=70, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
